# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ded5a63e-b615-485b-9a36-da5bda2dff63'
  imageRepository: 'project'
  containerRegistry: 'mycontrg.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Azure Pipelines
    steps:
    - task: Docker@2
      displayName: Build 
      inputs:
        command: build
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
        command: 'push'
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)