# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'd3c870ea-81b7-4309-8c9d-028d12a1dbe1'
  imageRepository: 'project'
  containerRegistry: 'mycontrg.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(dockerfilePath)/Dockerfile'
        tags: |
          $(tag)
- stage: push
  displayName: push stage
  jobs:
  - job: push
    displayName: push
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: push an image to container registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)