# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'SC-CR'
  imageRepository: '$(Build.Repository.Name):$(Build.BuildId)'
  containerRegistry: 'mycontrg.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build & push image 
  jobs:
  - job: Build
    displayName: Build & Push
    pool:
      name: Azure Pipelines
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: $(dockerfilePath)
        
    - task: Docker@2
      displayName: push an image to container registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)